name: Deploy de la pagina
on:
  push:
    branches:
      - main
jobs:
  deploy-page:
    runs-on: ubuntu-lastet
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: .
